FROM node:20
RUN adduser expense
RUN mkdir /opt/server
RUN chown expense:expense -R /opt/server
WORKDIR /opt/server
COPY package.json .
COPY *.js . 
RUN npm install
USER expense
CMD ["node" , "index.js"]
